# Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

# If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

powers = set()

for a in range(2, 101):
    for b in range(2, 101):
        powers.add(a**b)

print(len(powers))

# 9183